### ISSUE TITLE
Something broken related to mobile sensor

### ISSUE THREAD

**Issue by nafergo** [bryik/overunder-aframe#6]
Other A-frame examples I tried are running great but this has a very "shaky" camera. Seems that my movements with mobile phone are somehow exagerated, too sensitive.

**Comment by bryik** [comment]
I can reproduce, the camera goes crazy in the [drag-and-drop](https://bryik.github.io/overunder-aframe/dragdrop/) demo on my pixel 2.

Will take a look

**Comment by bryik** [comment]
I looked into this and the cause seems to be a change in the way [Chrome reports device rotation](https://github.com/aframevr/aframe/issues/3476). The fix *should* be as simple as upgrading to the latest version of A-Frame, however doing so caused something else to break (white screen).

When I have the time, I'll try and update this repo.

**Comment by zicopan** [comment]
any updates? re: the white screen due to latest version of A-frame

**Comment by bryik** [comment]
> any updates? re: the white screen due to latest version of A-frame

There must have been some change in Three.js...making [the image sphere material double sided](https://github.com/bryik/overunder-aframe/pull/7/commits/7af8955e6a3dbf052362fac701f9cc785903730b) fixed the white screen issue.

I want to do some refactoring before I merge the fix though.

**Comment by bryik** [comment]
OK, the [drag and drop example](https://bryik.github.io/overunder-aframe/dragdrop/) should be working again.

Had to remove the loading indicator as [three.js r84 dropped support for TextureLoader progress events.](https://threejs.org/docs/index.html#api/en/loaders/TextureLoader)
